openapi: 3.0.0
info:
  title: Basic Geo-api
  description: Api to list point
  version: 0.0.0
servers:
  - url: http://localhost:8080/api/v1
    description: Server local
paths:
  /point:
    get:
      summary: Returns a list of point.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of point names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string